name: restaurant
services:
    nestjs:
        build: .
        container_name: nestjs
        restart: always
        depends_on:
            - postgres
            - redis
        links:
            - postgres
            - redis
        volumes:
            - public-data:/app/public
            - logs-data:/app/logs
        networks:
            - network
        ports:
            - 3000:3000
    postgres:
        image: postgres:alpine
        container_name: postgres
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - network
        ports:
            - 5432:5432
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        volumes:
            - redis-data:/data
        networks:
            - network
        ports:
            - 6379:6379
volumes:
    public-data: {}
    logs-data: {}
    postgres-data: {}
    redis-data: {}
networks:
    network: {}